set1=set([1,2,3,4,5,6])
set2=set([4,5,6,7,8,9])
print("Union Representation")
print(set1.union(set2))
print("Intersection Representation")
print(set1.intersection(set2))
print("Symmetric difference Representation")
print(set1 - set2)
